-- Esquema local de desarrollo. Debe coincidir con las entidades JPA del proyecto.
-- Este archivo se ejecuta solamente al crear un volumen PostgreSQL vacio.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    permiso VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE carreras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    facultad VARCHAR(255) NOT NULL,
    duracion VARCHAR(255) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    estado VARCHAR(30) NOT NULL
);

CREATE TABLE planes_estudio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    vigencia_desde DATE NOT NULL,
    cantidad_asignaturas INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL,
    carrera_id BIGINT NOT NULL REFERENCES carreras(id),
    CONSTRAINT uk_plan_carrera_codigo UNIQUE (carrera_id, codigo)
);

CREATE TABLE asignaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    anio INTEGER NOT NULL,
    creditos INTEGER NOT NULL,
    carga_horaria INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL,
    plan_id BIGINT NOT NULL REFERENCES planes_estudio(id),
    CONSTRAINT uk_asignatura_plan_codigo UNIQUE (plan_id, codigo)
);

CREATE TABLE correlatividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asignatura_id BIGINT NOT NULL REFERENCES asignaturas(id),
    correlativa_id BIGINT NOT NULL REFERENCES asignaturas(id),
    tipo VARCHAR(30) NOT NULL,
    CONSTRAINT uk_correlatividad UNIQUE (asignatura_id, correlativa_id, tipo)
);

CREATE TABLE sedes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    direccion VARCHAR(255) NOT NULL,
    backoffice_site_id UUID UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE aulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nombre VARCHAR(255) NOT NULL DEFAULT '',
    backoffice_location_id UUID UNIQUE,
    tipo VARCHAR(30) NOT NULL DEFAULT 'AULA',
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    capacidad_maxima INTEGER NOT NULL,
    sede_id BIGINT NOT NULL REFERENCES sedes(id),
    CONSTRAINT uk_aula_sede_codigo UNIQUE (sede_id, codigo)
);

CREATE TABLE asignaciones_aula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aula_id BIGINT NOT NULL REFERENCES aulas(id),
    asignatura_id BIGINT NOT NULL REFERENCES asignaturas(id),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    cantidad_estudiantes INTEGER NOT NULL
);

CREATE TABLE periodos_academicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio INTEGER NOT NULL,
    numero INTEGER NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    inscripcion_desde DATE NOT NULL,
    inscripcion_hasta DATE NOT NULL,
    CONSTRAINT uk_periodo_anio_numero UNIQUE (anio, numero)
);

CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    asignatura_id BIGINT NOT NULL REFERENCES asignaturas(id),
    periodo_id BIGINT NOT NULL REFERENCES periodos_academicos(id),
    sede_id BIGINT NOT NULL REFERENCES sedes(id),
    modalidad VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    cupo_maximo INTEGER NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    turno VARCHAR(20) NOT NULL CHECK (turno IN ('TARDE', 'MAÑANA', 'NOCHE')),
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    CONSTRAINT ck_cursos_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT uk_curso_periodo_codigo UNIQUE (periodo_id, codigo)
);

CREATE TABLE curso_docentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    docente_id VARCHAR(100) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    CONSTRAINT uk_curso_docente UNIQUE (curso_id, docente_id)
);

CREATE TABLE inscripciones_curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    alumno_id VARCHAR(100) NOT NULL,
    fecha_inscripcion DATE NOT NULL,
    estado VARCHAR(30) NOT NULL,
    nota_final NUMERIC(4, 2),
    fecha_resultado DATE,
    CONSTRAINT uk_inscripcion_curso_alumno UNIQUE (curso_id, alumno_id)
);

CREATE TABLE horarios_curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    aula_id BIGINT NOT NULL REFERENCES aulas(id),
    dia_semana VARCHAR(20) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL
);

CREATE TABLE turnos_examen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    inscripcion_desde DATE NOT NULL,
    inscripcion_hasta DATE NOT NULL
);

-- Credenciales: admin@universidad.edu.ar / CambiarEstaClave123!
-- pgcrypto genera un hash BCrypt; el backend lo valida con BCryptPasswordEncoder.
INSERT INTO usuarios (nombre, email, password, permiso, activo)
VALUES ('Administrador', 'admin@universidad.edu.ar',
        crypt('CambiarEstaClave123!', gen_salt('bf', 12)), 'ADMINISTRATIVO', TRUE);

INSERT INTO carreras (codigo, nombre, facultad, duracion, titulo, estado)
VALUES ('LGTI', 'Licenciatura en Gestión de Tecnologías de la Información',
        'Facultad de Ingeniería y Ciencias Exactas', '4 años',
        'Licenciado/a en Gestión de Tecnologías de la Información', 'ACTIVA');

INSERT INTO planes_estudio (codigo, nombre, vigencia_desde, cantidad_asignaturas, estado, carrera_id)
SELECT 'LGTI-2026', 'Plan de estudios LGTI 2026', DATE '2026-01-01', 14, 'ACTIVA', id
FROM carreras WHERE codigo = 'LGTI';

INSERT INTO asignaturas (codigo, nombre, anio, creditos, carga_horaria, estado, plan_id)
SELECT datos.codigo, datos.nombre, datos.anio::INTEGER, 6, 64, 'ACTIVA', plan.id
FROM planes_estudio plan
CROSS JOIN (
    VALUES
      ('LGTI-101', 'Introducción a la Algoritmia', '1'),
      ('LGTI-102', 'Sistemas de Información I', '1'),
      ('LGTI-103', 'Arquitectura de Computadores', '1'),
      ('LGTI-104', 'Marketing', '1'),
      ('LGTI-105', 'Diseño y Desarrollo Web', '1'),
      ('LGTI-106', 'Algoritmos y Estructuras de Datos I', '1'),
      ('LGTI-107', 'Sistemas de Información II', '1'),
      ('LGTI-108', 'Sistemas Operativos', '1'),
      ('LGTI-109', 'Matemática Discreta', '1'),
      ('LGTI-110', 'Testing de Aplicaciones', '1'),
      ('LGTI-201', 'Algoritmos y Estructuras de Datos II', '2'),
      ('LGTI-202', 'Paradigma Orientado a Objetos', '2'),
      ('LGTI-203', 'Diseño y Análisis de Algoritmos', '2'),
      ('LGTI-204', 'Dirección de Proyectos de Tecnología', '2')
) AS datos(codigo, nombre, anio)
WHERE plan.codigo = 'LGTI-2026';
