spring.application.name=gestion-academica
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:h2:mem:gestionacademica;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

universidad.dominio-email=${UNIVERSIDAD_DOMINIO_EMAIL:universidad.edu.ar}
universidad.admin.email=${UNIVERSIDAD_ADMIN_EMAIL:admin@universidad.edu.ar}
universidad.admin.password=${UNIVERSIDAD_ADMIN_PASSWORD:CambiarEstaClave123!}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs

universidad.abrir-swagger-al-iniciar=${ABRIR_SWAGGER_AL_INICIAR:true}
